export const VEHICLE_OPTION_LABELS: Record<string, string> = {
  SEDAN: 'Седан',
  HATCHBACK: 'Хэтчбек',
  SUV: 'Внедорожник',
  COUPE: 'Купе',
  WAGON: 'Универсал',
  CONVERTIBLE: 'Кабриолет',
  VAN: 'Фургон',
  PICKUP: 'Пикап',
  OTHER: 'Другое',
  PETROL: 'Бензин',
  DIESEL: 'Дизель',
  ELECTRIC: 'Электрический',
  HYBRID: 'Гибрид',
  PLUG_IN_HYBRID: 'Подключаемый гибрид',
  LPG: 'Газ',
  HYDROGEN: 'Водород',
  MANUAL: 'Механическая',
  AUTOMATIC: 'Автоматическая',
  FWD: 'Передний',
  RWD: 'Задний',
  AWD: 'Полный',
  NEW: 'Новый',
  USED: 'С пробегом',
  DAMAGED: 'Повреждён',
  BLACK: 'Чёрный',
  WHITE: 'Белый',
  GRAY: 'Серый',
  SILVER: 'Серебристый',
  BLUE: 'Синий',
  RED: 'Красный',
  GREEN: 'Зелёный',
  BROWN: 'Коричневый',
  BEIGE: 'Бежевый',
  YELLOW: 'Жёлтый',
  ORANGE: 'Оранжевый',
  PURPLE: 'Фиолетовый',
};
